---
image: docker:stable-dind

stages:
  - Molecule

services:
  - docker:dind

before_script:
  - apk add --no-cache
    python3 python3-dev py3-pip gcc git curl build-base
    autoconf automake py3-cryptography linux-headers
    musl-dev libffi-dev openssl-dev openssh rsync ansible ansible-lint
  - docker info
  - python3 -m pip install molecule[docker]

Molecule:
  stage: Molecule
  script:
    - molecule test -- -t repo_init