---
image: docker:24.0.4-alpine3.18

stages:
  - Molecule

services:
  - docker:24.0.4-dind-alpine3.18

before_script:
  - echo -e "section_start:`date +%s`:before_script_sec[collapsed=true]\r\e[0KConfiguring molecule"
  - apk add --no-cache py3-pip
  - docker info
  - python3 -m pip install molecule molecule-plugins[docker]
  - echo -e "section_end:`date +%s`:before_script_sec\r\e[0K"

Molecule:
  stage: Molecule
  variables:
    ANSIBLE_FORCE_COLOR: "1"
    PY_COLORS: "1"
  script:
    - molecule test -- -t restic_repo_init