---
- name: Restic | Create restic user
  ansible.builtin.user:
    name: "{{ restic_user }}"
    group: "{{ restic_user_group }}"
    groups: "{{ restic_user_groups }}"
    create_home: "{{ restic_user_create_home }}"
    system: "{{ restic_user_system }}"
    home: "{{ restic_user_home }}"
    shell: "{{ restic_user_shell }}"
    update_password: on_create
  when:
    - restic_user_create

- name: Restic | Debian - Install acl package
  ansible.builtin.apt:
    name:
      - acl
    state: present
    update_cache: true
  when:
    - ansible_os_family == "Debian"

- name: Restic | RHEL - Install restic package
  ansible.builtin.yum:
    name:
      - acl
    state: present
    update_cache: true
  when:
    - ansible_os_family == "RedHat"
...
