---
- name: Restic | Debian - Install restic package
  ansible.builtin.apt:
    name:
      - restic
    state: present
    update_cache: true
  when:
    - ansible_os_family == "Debian"

- name: Restic | RHEL - Install restic package
  ansible.builtin.yum:
    name:
      - epel-release
      - restic
    state: present
    update_cache: true
  when:
    - ansible_os_family == "RedHat"

...
