- name: Install restic package
  ansible.builtin.package:
    name: restic
    state: present
    update_cache: true
  when:
    - restic_install_repo
    - not restic_install_binary

- name: Ensure bzip2 is installed
  ansible.builtin.package:
    name: bzip2
    state: present
  when:
    - restic_install_binary

- name: Set restic_url
  ansible.builtin.set_fact:
    restic_url: 'https://github.com/restic/restic/releases/download/v{{ restic_install_version }}/restic_{{ restic_install_version }}_{{ ansible_system | lower }}_{{ restic_install_architecture }}.bz2'
  when:
    - restic_install_binary

- name: Check if path exists
  ansible.builtin.stat:
    path: '{{ restic_install_binary_location }}/restic'
  register: result
  when:
    - restic_install_binary

- name: Download restic binary
  ansible.builtin.get_url:
    url: '{{ restic_url }}'
    dest: '{{ restic_install_download_location }}/restic.bz2'
    mode: 0500
    owner: '{{ restic_user }}'
    group: '{{ restic_group }}'
  when:
    - restic_install_binary
    - not result.stat.exists

- name: Decompress the binary
  ansible.builtin.shell: "bzip2 -dc {{ restic_install_download_location }}/restic.bz2 > {{ restic_install_binary_location }}/restic"
  args:
    creates: '{{ restic_install_download_location }}/restic'
  when:
    - restic_install_binary
    - not result.stat.exists

- name: Remove downloaded file
  ansible.builtin.file:
    path: '{{ restic_install_download_location }}/restic'
    state: absent
  when:
    - restic_install_binary
    - not result.stat.exists
    - "'FAILED' in restic_test_result.stderr"

- name: Ensure permissions are correct
  ansible.builtin.file:
    path: '{{ restic_install_binary_location }}/restic'
    mode: '{{ restic_install_binary_perms }}'
    owner: '{{ restic_user }}'
    group: '{{ restic_user_group }}'
  when:
    - restic_install_binary
    - not result.stat.exists

- name: Block | Test the binary
  block:
    - name: Test the binary
      ansible.builtin.command: "{{ restic_install_binary_location }}/restic version"
      ignore_errors: true
      register: restic_test_result
      failed_when: restic_test_result.rc == 0 or restic_test_result.rc >= 2
      when:
        - restic_install_binary
        - not result.stat.exists
  rescue:
    - name: Remove faulty binary
      ansible.builtin.file:
        path: '{{ restic_install_binary_location }}/restic'
        state: absent
      when:
        - restic_install_binary
        - not result.stat.exists

...
