---
dependency:
  name: galaxy
driver:
  name: ${DRIVER:-docker}

lint: ansible-lint

platforms:
  - name: debian-11-binary-cron
    image: docker.io/geerlingguy/docker-debian11-ansible
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: debian-11-repo-systemd
    image: docker.io/geerlingguy/docker-debian11-ansible
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: rocky-9-binary-systemd
    image: docker.io/geerlingguy/docker-rockylinux9-ansible
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: rocky-9-repo-cron
    image: docker.io/geerlingguy/docker-rockylinux9-ansible
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  inventory:
    host_vars:
      rocky-9-repo-cron:
        restic_backup_cron: true
      rocky-9-binary-systemd:
        restic_install_binary: true
      debian-11-binary-cron:
        restic_install_binary: true
        restic_backup_cron: true
    group_vars:
      all:
        restic_backup_keep:
          daily: 1
          weekly: 7
          monthly: 30
        restic_backup_filestobackup:
          - "/root/"
          - "/etc/"
        restic_backup_config:
          - RESTIC_REPOSITORY: "/backup"
          - RESTIC_PASSWORD: 'superStrongPassword'

verifier:
  name: ansible

...
